### ISSUE TITLE
Wrong link when updating

### ISSUE THREAD

**Issue by SannitaSSJ** [magnusmanske/listeria_rs#1]
When I click the link for a manual update from {{Wikidata list}}, I get a link to `https://wikidata.wikidata.org/wiki/$1`, which doesn’t work at all (the right link would be `https://www.wikidata.org/wiki/$1` or just `https://wikidata.org/wiki/$1`).

**Comment by magnusmanske** [comment]
Example page?

**Comment by fokky** [comment]
Oh, I now notice this is the same issue as #6 (but that one's on Commons). Example there.

**Comment by SannitaSSJ** [comment]
@magnusmanske if you need an example, the page is https://www.wikidata.org/wiki/User:Sannita/sandbox

**Comment by magnusmanske** [comment]
This is fixed now.
