### ISSUE TITLE
Listeriabot doesn't work on Dagwiki

### ISSUE THREAD

**Issue by DNShitobu** [magnusmanske/listeria_rs#104]
Several people have tried on implementing listeriabot tabular display on the dag.wikipedia.org but it either produces an error or loads forever. Kindly use [this](https://dag.wikipedia.org/wiki/8th_Parliament_of_the_4th_Republic_of_Ghana) as a case study. Please let me know if you have any further queries

**Comment by magnusmanske** [comment]
I added instructions to the README
