### ISSUE TITLE
ListeriaBot returns 504 Gateway Time-out - Webservice request timed out

### ISSUE THREAD

**Issue by LNBelo** [magnusmanske/listeria_rs#109]
Hi, Magnus.

It is no longer possible to update tables, since 2023-09-27 ListeriaBot (https://listeria.toolforge.org/) is returning the following error:

504 Gateway Time-out
nginx/1.14.2

**Comment by geertivp** [comment]
I have created a [Phabricator ticket](https://phabricator.wikimedia.org/T347672), that has been solved 30 minutes ago. Solution was not documented yet.

**Comment by magnusmanske** [comment]
Webservice silently breaking on Toolforge and not auto-restarting is a common issue. Apparently no one cares, or knows how to fix it. I wrote my own monitoring tool at https://magnustools.toolforge.org/tool_status.html and email alert but that doesn't always pick up issues.
