### ISSUE TITLE
Listeria will not update for "list of lists" on Wikidata

### ISSUE THREAD

**Issue by jane023** [magnusmanske/listeria_rs#11]
Message from update page: 
Trying to update Wikidata:WikiProject_sum_of_all_paintings/Catalog/Paintings_per_catalog...

./target/release/main 'www.wikidata.org' 'Wikidata:WikiProject_sum_of_all_paintings/Catalog/Paintings_per_catalog'

Done.
Return to Wikidata:WikiProject_sum_of_all_paintings/Catalog/Paintings_per_catalog

Also, check out the current bot status!

Status: OK
I checked the query in case the problem is a timeout, but it works. Also another list of lists (Hofstede de Groot catalogs) does update. For the problem list, see https://www.wikidata.org/wiki/Wikidata:WikiProject sum of all paintings/Catalog/Paintings per catalog

**Comment by Tagishsimon** [comment]
https://www.wikidata.org/wiki/Wikidata%3AWikiProject_sum_of_all_paintings%2FCatalog%2FPaintings_per_catalog ... seems not to have been cured by https://github.com/magnusmanske/listeria_rs/issues/4

**Comment by magnusmanske** [comment]
@jane023 Should be fixed now ([example](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_sum_of_all_paintings/Catalog/Paintings_per_catalog&oldid=1307414203)).

@Tagishsimon that was a different problem.
