### ISSUE TITLE
Currently clicking on "Manually update list" fails

### ISSUE THREAD

**Issue by backache** [magnusmanske/listeria_rs#111]
Currently clicking on "Manually update list" on an existing list in Wikipedia fails saying

`No webservice
The tool responsible for the URL you have requested, https://listeria.toolforge.org/index.php?action=update&project=wikidata&page=Talk:Q12345, is not currently responding.`

**Comment by ratonyi** [comment]
I have the same problem: "503 Service Unavailable"

**Comment by geertivp** [comment]
https://listeria.toolforge.org generates different errors:

Wikimedia Error: Wikimedia Toolforge Error: Our servers are currently experiencing a technical problem. This is probably temporary and should be fixed soon. Please try again later.

503 Service Unavailable: No webservice: The tool responsible for the URL you have requested, https://listeria.toolforge.org/, is not currently responding.

**Comment by backache** [comment]
Has been fixed now and the manual running seems to be queue-based rather immediate :-)
