### ISSUE TITLE
Manual updates not running?

### ISSUE THREAD

**Issue by p858snake** [magnusmanske/listeria_rs#117]
It's hard to tell as the status pages are blank, But are the manual update requests not running? I've tried a few different pages and it says its queue and will happen in a few minutes but nothing happens.

**Comment by stefano-1973** [comment]
**Manual and automatic updates are not running**, not only manual. No more updates for the wiki of all languages and also on wikidata. 
As p858snake asks, there isn't a way to know the result of the "now" asyncronous update ?

**Comment by stefano-1973** [comment]
Now wikidata is updating correctly. The ticket can be closed from my tests. Thank you

**Comment by stefano-1973** [comment]
From May 20, 2024 the listeria update NO longer works:

https://es.wikipedia.org/wiki/Anexo%3AVideoconsolas_de_primera_generaci%C3%B3n

**Comment by backache** [comment]
Today (30th May '24) it still has an issue and the status page is blank :-(

It'd be good to have some basic troubleshooting steps and who/how to message someone with server access to investigate as its not fair for it to all be on one person.

**Comment by backache** [comment]
Still seems not to be working :-(

**Comment by magnusmanske** [comment]
Should be working now
