### ISSUE TITLE
Lists not updating, or, manual update status does not indicate the SPARQL times out

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#12]
For the following 4 lists:

a) the SPARQL times out when run in WDQS

and the issue is:

b) A Listeria manual update yields a status page that suggests all is fine & that the page has been updated. however the page has not been updated, and if the cause is a SPARQL time out, that is not being reported.

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Actresses_-_country_%26_date_of_birth_unknown&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Painters_-_Rest_of_world&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Writers_-_Rest_of_world&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Writers_-_country_unknown&action=history

**Comment by magnusmanske** [comment]
Odd. Doesn't seem to be the SPARQL timing out though.

**Comment by Tagishsimon** [comment]
May be borderline? iirc in my tests this morning, these all timed out, but clearly they have had a history of running within the allocated time.

**Comment by magnusmanske** [comment]
Should be fixed now ([example](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Painters_-_Rest_of_world&oldid=989328186)) though in at least one case, the resulting wikitext is too large to be saved. This will show in the "manual update" result, and on the bot status page.
