### ISSUE TITLE
Today ListeriaBot going mad in several Wikipedias

### ISSUE THREAD

**Issue by pere-prlpz** [magnusmanske/listeria_rs#121]
Since a few hours ago, ListeriaBot is doing incorrect editions. Most of its contributions in several Wikipedias (I've checked cawiki, eswiki and frwiki) seem to be deleting large parts of lists, and in automated lists with row templates it is getting the fields wrong. The errors seem to be at random, because when manually clicking on the update button it generates a different random list - I mean a list from the same query but with a lot of missing elements.

I suspect something has changed in the bot script about 13:00 CEST.

**Comment by pere-prlpz** [comment]
Some examples:

https://ca.wikipedia.org/w/index.php?title=Llista_de_top%C3%B2nims_de_Pin%C3%B3s&action=history

https://es.wikipedia.org/w/index.php?title=Wikiproyecto:LGBT/Solicitados/Pa%C3%ADses/Asia&diff=prev&oldid=160604471

https://fr.wikipedia.org/w/index.php?title=Projet:AfroCreatives/Articles_%C3%A0_Cr%C3%A9er/%C3%89gypte&diff=prev&oldid=215761636

**Comment by sjoerddebruin** [comment]
Another example https://www.wikidata.org/w/index.php?title=User:Sjoerddebruin/Geen_geboortedatum_op_nlwiki&action=history

**Comment by Theklan** [comment]
The same thing is happening here. Content is removed randomly and fields in the rows are not used as they should.
https://eu.wikipedia.org/wiki/Berezi:Ekarpenak/ListeriaBot

**Comment by JAnDud** [comment]
Bot is not updating but destroying lists, now is blocked on cs.wiki

**Comment by pere-prlpz** [comment]
If I knew that this problem were going to last, I'd ask cawiki admins to provisionally block the bot, too.

**Comment by magnusmanske** [comment]
Should be fixed now. Please re-open if there are still issues.
