### ISSUE TITLE
How to get the English Wikipedia article name?

### ISSUE THREAD

**Issue by prototyperspective** [magnusmanske/listeria_rs#134]
In [this gallery](https://commons.wikimedia.org/wiki/WikidataGalleries/MusicGenres/Main) on Commons I'd like to simply get the English Wikipedia article title so I can add a link to it. Other languages may get added later and it should also show an item when there is no ENWP article for it, this is just about adding a link if it exists.

I could not find info on how to retrieve a Wikipedia article title [here](https://en.wikipedia.org/wiki/Template:Wikidata_list). [Also selecting ?articlename](https://commons.wikimedia.org/w/index.php?title=WikidataGalleries%2FMusicGenres%2FMain&diff=935823560&oldid=935354071) didn't work. I also couldn't find a useful examples in [the sparql examples](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples) because I want to show the item also if no ENWP article exists. The query in the linked diff shows only items that have an ENWP article and even there I can't get it into a column.

**Comment by pere-prlpz** [comment]
I think you can get more help at https://www.wikidata.org/wiki/Wikidata:Request_a_query

Anyway, the solution to get articles with or without enwiki sitelink is to use OPTIONAL.

**Comment by prototyperspective** [comment]
Thanks for the info. Saying OPTIONAL is quite ambiguous. For instance, I had to first learn what it means and I don't wish to learn sparql because I have other Wikimedia things to do. However, [this query](https://commons.wikimedia.org/w/index.php?title=WikidataGalleries%2FMusicGenres%2FMain&diff=937214000&oldid=936991362) seems to work and does return the Wikipedia articles. However, as you can see in that diff the bot does not add this as a column to to the templates.

**Comment by prototyperspective** [comment]
@pere-prlpz Okay another thing I just found is `?fieldname, a SPARQL result field name (variable).` in [the template documentation](https://en.wikipedia.org/wiki/Template:Wikidata_list) so now it adds the link to a new column. I don't yet know how to make it return an internal link – if you know how please let me know. I think I can solve this from there so I'm closing this issue already, thank you!

**Comment by pere-prlpz** [comment]
If you want to get a link, you can use links=text in the template, but that will be links to the wiki where the list is (e.g. links to Commons galleries if the page is in Commons). I suppose it's possible to link a specific Wikipedia but that needs to be worked in the query.

For questions about the query, it's better to ask at https://www.wikidata.org/wiki/Wikidata:Request_a_query , even if you don't want to learn SPARQL - although I recommend learning some SPARQL if you want to work with Wikidata.

**Comment by prototyperspective** [comment]
This was solved with this workaround in the template:
```
{{tooltip|Wikipedia|Article on English Wikipedia (global)}}: {{#if: {{{article|}}} |[[{{#invoke:String|replace|source={{{article}}}|pattern=https://en.wikipedia.org/wiki/ |replace=w:}}|{{#invoke:String|replace|source={{#invoke:String|replace|source={{{article}}}|pattern=https://en.wikipedia.org/wiki/ |replace=}}|pattern=_|replace=<nowiki> </nowiki>}}]]|(no article/section yet)}}
```
It's absurd that this workaround is needed rather than wikilinking being supported by this tool but it works (you can see the gallery linked above). However, one can't use it when using the default table. See the issue 138 I just created.
