### ISSUE TITLE
as non-empty expected list updated with no content

### ISSUE THREAD

**Issue by camelCaseNick** [magnusmanske/listeria_rs#14]
The list at https://www.wikidata.org/wiki/Special:PermanentLink/1308147407 was replaced with the empty list by ListeriaBot v2. An unusual aspect of the list might be the creation of XML-/HTML-like MediaWiki tags within the query.

**Comment by Jheald** [comment]
Also https://en.wikipedia.org/wiki/Talk%3AList_of_Royal_Academicians%2FARAs

**Comment by magnusmanske** [comment]
These are both working now.
