### ISSUE TITLE
Lists now including properties in addition to items, properties resolve to "page does not exist"

### ISSUE THREAD

**Issue by CECSpecialistI** [magnusmanske/listeria_rs#15]
One of the lists in question is [here](https://www.wikidata.org/wiki/Wikidata%3AWikiProject_PCC_Wikidata_Pilot%2FUniversity_of_Washington%2FItems_Created_or_Edited)
These lists previously only included wikidata items in their results. Now they are also including wikidata properties, but there is something going on with how the results are generated that gives me a "page does not exist" (screenshots below). 

I think this is making it impossible to filter them out using SPARQL. I tried a number of queries today without success, and sometimes had trouble getting the bot to populate any results at all so I just put my original query back. Thanks for creating and maintaining this tool @magnusmanske !
![listeriaIssue2](https://user-images.githubusercontent.com/43214565/99475940-75545080-2904-11eb-9c18-7e48be3059ec.JPG)
![listeriaIssue](https://user-images.githubusercontent.com/43214565/99475798-25758980-2904-11eb-96a8-8e0b8a36d70c.JPG)

**Comment by magnusmanske** [comment]
Thanks, this is fixed now ([example](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_PCC_Wikidata_Pilot/University_of_Washington/Items_Created_or_Edited&oldid=1308380786)).
