### ISSUE TITLE
Category added wrongly

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/listeria_rs#16]
https://en.wikipedia.org/w/index.php?title=User_talk:Magnus_Manske&diff=989330639&oldid=989327330

**Comment by magnusmanske** [comment]
*Example: [https://hu.wikipedia.org/w/index.php?title=Szerkeszt%C5%91:Palotabar%C3%A1t/Seg%C3%A9dletek/Diplom%C3%A1cia/Magyar_nagyk%C3%B6veti_c%C3%ADmek&oldid=23256871 November 15 (V2)] (at the bottom of the categories) Category link: <code>Kategória:Magyarország követei, nagykövetei Azerbajdzsánban</code>
*Good version: [https://hu.wikipedia.org/w/index.php?title=Szerkeszt%C5%91:Palotabar%C3%A1t/Seg%C3%A9dletek/Diplom%C3%A1cia/Magyar_nagyk%C3%B6veti_c%C3%ADmek&oldid=22869441 October 15 (V1)] Category link: <code>:Kategória:Magyarország követei, nagykövetei Azerbajdzsánban</code>

**Comment by magnusmanske** [comment]
Apparently, ListeriaBot is now blocked from editing on hu.wikipedia.org?

**Comment by magnusmanske** [comment]
The actual bug is fixed now ([example](https://en.wikipedia.org/w/index.php?title=User:Magnus_Manske/listeria_test1&oldid=989861337)), so I'm closing this issue.

**Comment by ratonyi** [comment]
> Apparently, ListeriaBot is now blocked from editing on hu.wikipedia.org?

Yes, see also: [https://github.com/magnusmanske/listeria_rs/issues/20].
Thanks for category repair!
