### ISSUE TITLE
Not performing a manual update after SPARQL has been altered

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#17]
afaics, based on playing with https://en.wikipedia.org/wiki/Wikipedia%3AWikiProject_Women_in_Red%2FMissing_articles_by_occupation%2FSculptors Listeria is not allowing a manual update to be performed, after the page's SPARQL has been altered, if the page was recently manually updated.

So the sequence should be:
- run manual update
- change SPARQL
- run manual update - update runs, page is refreshed based on changes SPARQL

What seems to be happening is
- run manual update
- change SPARQL
- run manual update - update returns a status screen, as below, immediately; page is not updated.

Trying to update Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Sculptors...
Done.
Return to Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Sculptors

Also, check out the current bot status!
Status: OK

**Comment by magnusmanske** [comment]
[Fixed now](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Sculptors&oldid=989675217).
