### ISSUE TITLE
Property and qualifier both showing when it used to be just the qualifier

### ISSUE THREAD

**Issue by loraxian** [magnusmanske/listeria_rs#18]
I used to just have the qualifier listed, now I get the qualifier value and the property it is qualifying
So in this table https://en.wikipedia.org/wiki/User:DrThneed/Listeria_for_Hokitika the "Date listed" column was just a date (value of P580, qualifier on P1435), now since the update it is showing the values of the P580 and the P1435.

**Comment by Tagishsimon** [comment]
By my reading of the documentation, V2 now seems to be doing what it says on the tin, whereas V1 was not. So arguably it's a fixed bug:

"Pxxx/Pzzz, qualifier properties; for Pxxx linking to an item Qyyy and having a Pzzz qualifier, the Qxxx linked label and the value of Pzzz"

https://en.wikipedia.org/wiki/Template:Wikidata_list

If you want the qualifier only, you'd have to tweak the sparql and get it via a ?fieldname.

**Comment by Tagishsimon** [comment]
But whilst we have you here, Magnus, in he above report is the column P6375:Street address meant to emit a vaiue in a form starting with a language identifier, like so?

en:Acacia Avenue, Slough

**Comment by tmtmtmtm** [comment]
this also heavily impacts reports on members of legislatures, where most of the relevant information is in qualifiers: see for example, https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/Northern_Ireland/data/Assembly/5th_Assembly  (vs earlier https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_every_politician/Northern_Ireland/data/Assembly/5th_Assembly&oldid=1253275686)

**Comment by magnusmanske** [comment]
I have changed the behaviour of "p_q_p" to mirror V1 ([example](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_every_politician/Northern_Ireland/data/Assembly/5th_Assembly&oldid=1309704652)).
