### ISSUE TITLE
generated columns no longer always apply to ?item

### ISSUE THREAD

**Issue by tmtmtmtm** [magnusmanske/listeria_rs#19]
https://www.wikidata.org/wiki/Wikidata:WikiProject_Parliaments/lists/national_legislatures produces a list of countries and their legislatures, and includes a column list of:

```
|columns=?country:Country,label,description,P31,P1342,P527,P18,P856
```

Previously, the label, description, and Pxxx calls all applied to the `?item` (i.e. the legislature), but now they seem to apply to the `?country` instead: https://www.wikidata.org/w/index.php?title=Wikidata%3AWikiProject_Parliaments%2Flists%2Fnational_legislatures&type=revision&diff=1309295158&oldid=1264791914

**Comment by magnusmanske** [comment]
This is [fixed now](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_Parliaments/lists/national_legislatures&oldid=1309676354).

**Comment by tmtmtmtm** [comment]
Great, thanks.
