### ISSUE TITLE
Bluelinks (to wikidata) appear though |links=red parameter is set

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#2]
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_dictionary/Grove_Art

Bluelinks (with URLs pointing to wikidata) appearing in the first column; don't think they should be there. Have never seen such things in my Listeria experience.

**Comment by magnusmanske** [comment]
This is fixed now ([example](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_dictionary/Grove_Art&oldid=988847161)).
