### ISSUE TITLE
Create double lists

### ISSUE THREAD

**Issue by ratonyi** [magnusmanske/listeria_rs#20]
Listeriabot unexpectedly started duplicating the lists, that's why it was banned from Hungarian Wikipedia :( There is a line of HTML code between the two tables.

Example: 

1. [https://hu.wikipedia.org/w/index.php?title=Indiana_megy%C3%A9inek_list%C3%A1ja&oldid=23273420](url)
2. [https://hu.wikipedia.org/w/index.php?title=TER_Alsace&oldid=23273403](url)
3 [https://hu.wikipedia.org/wiki/Kateg%C3%B3riavita:P%C3%A1rizsban_j%C3%A1tsz%C3%B3d%C3%B3_filmek](url)

HTML code fragment (CTRL+F search): `sparql=SELECT ?item WHERE`...

Start (first error): 2020. november 20., 19:25

**Comment by magnusmanske** [comment]
I think it was fixed in #16 ([example](https://hu.wikipedia.org/w/index.php?title=Indiana_megy%C3%A9inek_list%C3%A1ja&oldid=23278945)). I believe you can unblock the bot again.
