### ISSUE TITLE
problematic css classes

### ISSUE THREAD

**Issue by JAnDud** [magnusmanske/listeria_rs#23]
when page uses template for formatting otput, icluded styles breaks output:

https://cs.wikipedia.org/w/index.php?title=Wikipedie:WikiProjekt_Drobné_památky/okres_České_Budějovice/Boršov_nad_Vltavou&curid=1609407&diff=19182032&oldid=19116942&diffmode=source

please, don't include classses when  row_template = yes

**Comment by magnusmanske** [comment]
Duplicate of #27
