### ISSUE TITLE
 ListeriaBot V2 query does not produce output any more 

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/listeria_rs#25]
IMPORTED FROM https://bitbucket.org/magnusmanske/listeria/issues/80/listeriabot-v2-query-does-not-produce

Geert Van Pamel:

A query that previously ran OK, does not produce output any more.

The Bot status still shows an OK, but no new version of the Wiki page is produced.

241. Wikipedia:Wikiproject/Belgische podiumkunsten/Dans Vrouwen in rood/ListeriaBot/Blauwe linken (OK; 2020-11-21 01:08:15)

Permalink: https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Belgische_podiumkunsten/Dans_Vrouwen_in_rood/ListeriaBot/Blauwe_linken&oldid=57583773

No other error is shown. What happens?

**Comment by geertivp** [comment]
Seem to be OK now.
