### ISSUE TITLE
 Output to template is broken because of table tyles 

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/listeria_rs#27]
IMPORTED FROM https://bitbucket.org/magnusmanske/listeria/issues/78/output-to-template-is-broken-because-of

when page uses template for formatting otput, icluded styles breaks output:

https://cs.wikipedia.org/w/index.php?title=Wikipedie:WikiProjekt_Drobné_památky/okres_České_Budějovice/Boršov_nad_Vltavou&curid=1609407&diff=19182032&oldid=19116942&diffmode=source

**Comment by matejsuchanek** [comment]
This is duplicate of #23.

**Comment by magnusmanske** [comment]
Fixed.
