### ISSUE TITLE
Use of variable starting with uppercase prevents data being used in column

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#3]
Problem is evidenced on versions of https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_dictionary/Grove_Art

The SPARQL in the query selects a variable, which is then used as a column.

When the variable name is ?entry all is fine - desired values appear in the column.

When the variable name is ?Entry the column is blank.

See https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_dictionary/Grove_Art&action=history

variable name set to ?entry in 00:05, 13 November 2020
Listeria populates column in 00:06, 13 November 2020 update
variable name set to ?Entry in 00:24, 13 November 2020
Listeria blanks column in 00:24, 13 November 2020 update

**Comment by magnusmanske** [comment]
Seems fixed now ([example](https://en.wikipedia.org/w/index.php?title=User:Magnus_Manske/listeria_test1&oldid=988504135)).
