### ISSUE TITLE
Listeria fails to write output page

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#4]
I think this is unconnected with the Rust update - was happening before, is still happening.

Example report having issue: https://en.wikipedia.org/wiki/Wikipedia%3AWikiProject_Women_in_Red%2FMissing_articles_by_occupation%2FPoliticians_-_country_unknown

Issue is, valid SPARQL, but an a manual update Listeria gets no further than saying:

Trying to update Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Politicians_-_country_unknown...
Return to Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Politicians_-_country_unknown
Also, check out the current bot status!
Status: OK

It does not actually write the output page - see https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Politicians_-_country_unknown&action=history

**Comment by SannitaSSJ** [comment]
Similar to bug #1 - I had the same problem, and I thought it might've affected only WD...

**Comment by fokky** [comment]
I seem to have the same issue on Commons, when creating a new Listeria page like this one:

https://commons.wikimedia.org/wiki/User:Spinster/WikiFlix/Directed_by_female_directors (do note it uses a row template)

Or when I ask the bot to update an existing very similar page:

https://commons.wikimedia.org/w/index.php?title=User:Spinster/WikiFlix/Directed_by_Sergei_Eisenstein&action=history failed to update after clicking 'Manually update list'

**Comment by magnusmanske** [comment]
This ia sll fixed now.
