### ISSUE TITLE
Listeria not populating newly created list

### ISSUE THREAD

**Issue by jenyoung** [magnusmanske/listeria_rs#41]
I created a [page ](https://www.wikidata.org/wiki/User:Nashona/guggenheim)using listeria bot and it's not populating. 
Manually updating gives the message below and still doesn't populate it. My query returns results so I do not think it's the query.

<img width="271" alt="2020-12-10_101234" src="https://user-images.githubusercontent.com/2250501/101798116-5e061e80-3ad0-11eb-99c8-137ad18461b4.png">

**Comment by matejsuchanek** [comment]
Works with `LIMIT 100`. Either it's a too heavy dataset or some piece of data is causing an error.

**Comment by magnusmanske** [comment]
Interesting one. Gives me a mutex lock error when running from shell. Investigationg.

**Comment by magnusmanske** [comment]
The error is `ERROR: The content you supplied exceeds the article size limit of 2048 kilobytes.`. MediaWIki limit. I'll try to make the error show better.
