### ISSUE TITLE
Sections by binded variable not working anymore

### ISSUE THREAD

**Issue by papuass** [magnusmanske/listeria_rs#5]
See this edit:

https://lv.wikipedia.org/w/index.php?title=Valsts_aizsarg%C4%81jamie_kult%C5%ABras_pieminek%C4%BCi_Balvu_novad%C4%81&diff=3322163&oldid=3321163&diffmode=source

Query used:
https://query.wikidata.org/#SELECT%20%09%0A%09%3Fitem%20%3Fname%20%3Flat%20%3Flong%20%3Ftypelabel%20%3Fvaid%20%3Fyear%20%3Fimage%20%3Fcommonscat%20%3Fmunicipality%0A%09%3Fdistrict%20%3Flocality%20%3Fcomplex%20%3Fregion%20%3Faddress%20%3Fwikipediauri%20%3Fextlink%20%3Fmunwiki%0AWHERE%0A%7B%0A%09VALUES%20%3FcurrList%20%7B%20wd%3AQ20565700%20%7D%20.%0A%09VALUES%20%3FcurrNovads%20%7B%20wd%3AQ2018672%20%7D%20.%0A%09%3FcurrNovads%20wdt%3AP300%20%3Fregion%20.%0A%09%3Fitem%20wdt%3AP2817%20%3FcurrList%20.%0A%09%3Fitem%20wdt%3AP2494%20%3Fvaid%20.%0A%09%3Fitem%20wdt%3AP1435%20%3Ftype%20.%0A%09%3Fitem%20wdt%3AP131%20%3Fmunid.%0A%09%3Fmunid%20wdt%3AP131%20%3Fupmunid%20.%20%20%0A%09%3Fmunid%20wdt%3AP131%2a%20%3FcurrNovads%20.%0A%09%3Fupmunid%20wdt%3AP31%20%3Fupmuntype%20.%20%20%0A%09BIND%20%28%20IF%20%28%20%28%20%3Fupmuntype%20%3D%20wd%3AQ2577184%29%20%2C%20%3Fupmunid%20%2C%20%3Fmunid%20%29%20%20AS%20%3Fnovads%20%29%20.%0A%09%3Fmunsitelink%20schema%3Aabout%20%3Fmunid%20.%0A%09%3Fmunsitelink%20schema%3AinLanguage%20%22lv%22%20.%0A%09BIND%28STRAFTER%28str%28%3Fmunsitelink%29%2C%20%22lv.wikipedia.org%2Fwiki%2F%22%29%20AS%20%3Fmunwiki%29%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3Fcommonscat%20%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP2795%20%3Flocality%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP361%20%3Fcomplex%20%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20p%3AP571%20%3Finception%20.%20%3Finception%20pq%3AP1932%20%3Fyear%20%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic%20.%20BIND%28STRAFTER%28str%28%3Fpic%29%2C%20%22Special%3AFilePath%2F%22%29%20AS%20%3Fimage%29%20.%20%7D%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP856%20%3Fextlink%20%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP6375%20%3Faddress%20%7D%20.%0A%09OPTIONAL%20%7B%20%3Fitem%20wdt%3AP625%20%3Fcoord%20.%0A%09%09%3Fitem%20p%3AP625%20%3Fcoordinate%20.%0A%09%09%3Fcoordinate%20psv%3AP625%20%3Fcoordinate_node%20.%0A%09%09%3Fcoordinate_node%20wikibase%3AgeoLatitude%20%3Flat%20.%0A%09%09%3Fcoordinate_node%20wikibase%3AgeoLongitude%20%3Flong%20.%20%7D%0A%09OPTIONAL%20%7B%20%3Fsitelink%20schema%3Aabout%20%3Fitem%20.%20%3Fsitelink%20schema%3AinLanguage%20%22lv%22%20%0A%09%09BIND%28strafter%28str%28%3Fsitelink%29%2C%22%2Fwiki%2F%22%29%20as%20%3Fwikipediauri%29%20%7D%0A%09%3Fitem%20rdfs%3Alabel%20%3Fname%20.%20FILTER%28lang%28%3Fname%29%3D%22lv%22%29%0A%09%3Ftype%20rdfs%3Alabel%20%3Ftypelabel%20.%20FILTER%28lang%28%3Ftypelabel%29%3D%22lv%22%29%0A%09%3Fmunid%20rdfs%3Alabel%20%3Fmunicipality%20.%20FILTER%28lang%28%3Fmunicipality%29%3D%22lv%22%29%0A%09%3Fnovads%20rdfs%3Alabel%20%3Fdistrict%20.%20FILTER%28lang%28%3Fdistrict%29%3D%22lv%22%29%0A%7D

**Comment by magnusmanske** [comment]
Fixed now ([example](https://en.wikipedia.org/w/index.php?title=User:Magnus_Manske/listeria_test1&oldid=988506776)).

**Comment by papuass** [comment]
It seems that a different bug was fixed (and thanks for that!).

Previously this list had section headings from binded variable ?district.
https://lv.wikipedia.org/w/index.php?title=Valsts_aizsarg%C4%81jamie_kult%C5%ABras_pieminek%C4%BCi_Balvu_novad%C4%81&oldid=3321163

The current version does not have the section headings.
https://lv.wikipedia.org/w/index.php?title=Valsts_aizsarg%C4%81jamie_kult%C5%ABras_pieminek%C4%BCi_Balvu_novad%C4%81&oldid=3324867

**Comment by papuass** [comment]
OK, there is an issue for that: #28
