### ISSUE TITLE
Automatic working on Dutch Wikipedia

### ISSUE THREAD

**Issue by Ronnie-V** [magnusmanske/listeria_rs#58]
Until 22 December 2020, Listeria updated lists at the Dutch Wikipedia on a daily basis. 
As can be seen [https://nl.wikipedia.org/wiki/Speciaal:Bijdragen/ListeriaBot], the number of edits since that date is minimal.
Is there a special reason this does not work any more?

**Comment by magnusmanske** [comment]
Not sure why this stopped. Has picked up again.
