### ISSUE TITLE
Listeria's Toolforge 'output page' links to https://commons.commons.org, not https://commons.wikimedia.org

### ISSUE THREAD

**Issue by fokky** [magnusmanske/listeria_rs#6]
Steps to reproduce:

Take a Listeria list on Commons, e.g. this one 

https://commons.wikimedia.org/wiki/User:Spinster/WikiFlix/Films_from_France

Click 'Manually update list'

The 'output page' on Toolforge then produces a hyperlink to https://commons.commons.org/wiki/User%3ASpinster%2FWikiFlix%2FFilms_from_France which should be https://commons.wikimedia.org/wiki/User%3ASpinster%2FWikiFlix%2FFilms_from_France

**Comment by SannitaSSJ** [comment]
@magnusmanske please also take a look at #1 and #4 which are basically similar

**Comment by magnusmanske** [comment]
Fixed now.
