### ISSUE TITLE
Listeriabot execution "Killed by OS for overloading memory"

### ISSUE THREAD

**Issue by Deborahjay** [magnusmanske/listeria_rs#66]
Since the last successful Listeriabot update on 21 December 2020, all [my] manual attempts to start Listeriabot for updating the following English-language Women in Red page (https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_nationality/Israel), which has ca. 4.5K line items, fails with this message: 
* Trying to update Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_nationality/Israel...
* Killed by OS for overloading memory
Note: The parallel page in the Italian WP, with even more line items (presently 5K), had a similar difficulty with my numerous attempts, but it succeeded in an update on 31 January and again on 28 February (https://it.wikipedia.org/w/index.php?title=Progetto:WikiDonne/Liste_voci_mancanti_per_nazionalit%C3%A0/Israele&action=history ) . 
I can provide more information if necessary. This was noted on Wikidata User talk:Magnus Manske (https://www.wikidata.org/wiki/Topic:W2ds0jjottpho6rl) on 28 January with several updates, and the English Wikipedia User talk:Magnus Manske (https://en.wikipedia.org/wiki/User_talk:Magnus_Manske#Listeriabot_aborts_update_of_Women_in_Red_page_for_over_two_months) on March 1, before came here to try opening a GitHub issue. Thank you.

**Comment by CECSpecialistI** [comment]
Hello @magnusmanske thank you for creating Listeria! We've been using it at the University of Washington Libraries with great success as part of the international [PCC Wikidata Pilot Project](https://www.wikidata.org/wiki/Wikidata:WikiProject_PCC_Wikidata_Pilot). Many other participating libraries are using Listeria in the same way. The lists are valuable to us for showing others in the library world the usefulness of Wikidata and documenting the impact of our project. We are receiving the same message for [this list](https://www.wikidata.org/wiki/Wikidata%3AWikiProject_PCC_Wikidata_Pilot%2FUniversity_of_Washington%2FItems_Created_or_Edited). @Deborahjay are you still experiencing this issue for your Women in Red list? 

![listeriaIssue1](https://user-images.githubusercontent.com/43214565/113427876-ae103600-938a-11eb-974e-fe2152d3aedf.JPG)
![listeriaIssue2](https://user-images.githubusercontent.com/43214565/113427878-aea8cc80-938a-11eb-88b8-abedc75b3a57.JPG)

**Comment by sc113** [comment]
Same happens with https://www.wikidata.org/wiki/Wikidata%3AWikiProject_Music%2FLists%2FInstance_of_music_genre

**Comment by Tagishsimon** [comment]
fwiw, there's been a very substantial drop-off in Listeria updates - this chart for en-wikipedia. Seems mainly to be the Killed by OS for overloading memory issue, based on observing manually triggered updates.

<img width="812" alt="Screenshot 2021-05-03 at 21 52 50" src="https://user-images.githubusercontent.com/9000789/116933709-d5914180-ac5b-11eb-9ad6-af72ee03406a.png">

**Comment by Tagishsimon** [comment]
From https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Women_in_Red#Workaround_to_ListeriaBot_crashes

ListeriaBot sometimes crashes with the error "Killed by OS for overloading memory" and fails to update some redlists. This seems to be due to an implementation problem with handling large linked entities. This is not related to the complexity of the SPARQL query. In our redlists, it is possible to get rid of the error by removing some columns that link to geographical entities. So far I'm removing place of death (P20) where I encounter this problem.

If that helps.

**Comment by lirazelf** [comment]
Hi Magnus, I'm also getting this error here: https://sco.wikipedia.org/wiki/Uiser:Sara_Thomas_(WMUK)/sandbox/Listeria - any help would be appreciated :)

**Comment by sc113** [comment]
This solves the problem in most cases:

> I changed the query and now it works. Unfortunately, the issue is understandable: memory overload is probably caused by inclusion of countries (and maybe other territories). Countries have a lot of labels and statements; and when loaded at least with the most intuitive way - by URLs like http://www.wikidata.org/entity/Q30.json - it loads a JSON of >1MB size each, which probably causes memory overload. The solution is extract country-related labels with SPARQL instead of "columns" parameter. 
--Lockal (talk) 21:02, 3 February 2021 (UTC) @  [Template_talk:Wikidata_list](https://www.wikidata.org/wiki/Template_talk:Wikidata_list#Listeria_+_WikidataList_v2)

**Comment by rtargenton** [comment]
> This solves the problem in most cases:
> 
> > I changed the query and now it works. Unfortunately, the issue is understandable: memory overload is probably caused by inclusion of countries (and maybe other territories). Countries have a lot of labels and statements; and when loaded at least with the most intuitive way - by URLs like http://www.wikidata.org/entity/Q30.json - it loads a JSON of >1MB size each, which probably causes memory overload. The solution is extract country-related labels with SPARQL instead of "columns" parameter.
> > --Lockal (talk) 21:02, 3 February 2021 (UTC) @  [Template_talk:Wikidata_list](https://www.wikidata.org/wiki/Template_talk:Wikidata_list#Listeria_+_WikidataList_v2)

Not mine, a quite simple list is not working:
https://commons.wikimedia.org/wiki/Commons%3AWiki_Loves_Earth_in_Brazil%2FLista%2FAnimais

**Comment by pere-prlpz** [comment]
Same problem in cawiki. Lists that used to work some time ago stopped working with this error.

**Comment by magnusmanske** [comment]
The way this works has changed, this error won't happen again.
