### ISSUE TITLE
Sections are no longer working with complex queries

### ISSUE THREAD

**Issue by SannitaSSJ** [magnusmanske/listeria_rs#67]
We rely on Wikidata list for Wiki Loves Monuments lists every year. Unfortunately, since v2 update, the "section" parameter does not work any more. Here's an example: https://it.wikipedia.org/wiki/Progetto:Wiki_Loves_Monuments_2021/Monumenti/Valle_d%27Aosta

The expected result should be that every municipality with at least one monument (i.e. `|section=p131 |min_section=1`) appears within its own section. This is no longer the case. Any suggestions?

**Comment by magnusmanske** [comment]
Fixed now.
