### ISSUE TITLE
Creates categories instead of category links

### ISSUE THREAD

**Issue by GoingBatty** [magnusmanske/listeria_rs#88]
https://en.wikipedia.org/w/index.php?title=User:Jura1/pages_with_Wikidata_items_without_any_statements is incorrectly included in multiple article categories.  Could the bot please output category links instead of categories?  (e.g. [[:Category:Association football clubs established in 2022]] with a leading colon instead of [[Category:Association football clubs established in 2022]])
Thanks!

**Comment by magnusmanske** [comment]
This example doesn't work anymore, do you have another one?

**Comment by GoingBatty** [comment]
Sorry - I don't recall what bot this is referring to.
