### ISSUE TITLE
Manual update incorrectly zeros table

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#9]
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Violinists

should have ~940 rows.

A manual update just now produced zero rows.

https://en.wikipedia.org/w/index.php?title=Wikipedia%3AWikiProject_Women_in_Red%2FMissing_articles_by_occupation%2FViolinists&type=revision&diff=988739247&oldid=974668899

The WDQS report for the SPARQL in the list gives ~940 rows.

**Comment by magnusmanske** [comment]
This is fixed now ([example](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Violinists&oldid=988859765)).

**Comment by Tagishsimon** [comment]
@magnusmanske - another example of an update zeroing the page just now; SPARQL gives ~190 rows.

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Aviators&action=history

**Comment by Tagishsimon** [comment]
Or maybe not. The update was yesterday, before your fix. My mistake.
