### ISSUE TITLE
Bot not human

### ISSUE THREAD

**Issue by Llywelyn2000** [magnusmanske/listeria_rs#91]
We've registered this as a bot on cywiki, yet, [https://cy.wikipedia.org/wiki/Arbennig:RecentChanges?hidebots=1&hidecategorization=1&hideWikibase=1&limit=500&days=14&enhanced=1&urlversion=2 it still appears as human edits on Recent Changes].  If we need to do anything else to hide the edits, pls let me know.  ~~~~

**Comment by magnusmanske** [comment]
Using botflag now

**Comment by Llywelyn2000** [comment]
Many thanks Magnus!
