### ISSUE TITLE
Broken list on ptwiki

### ISSUE THREAD

**Issue by BonasDaniel** [magnusmanske/listeria_rs#93]
Hi, Magnus,

‌

I think the version 2 has broken several listeria lists on the Portuguese Wikipedia.

For example: [https://pt.wikipedia.org/wiki/Wikip%C3%A9dia%3AWikidata%2FAnivers%C3%A1rio_hoje]
(https://pt.wikipedia.org/wiki/Wikip%C3%A9dia%3AWikidata%2FAnivers%C3%A1rio_hoje)

**Comment by magnusmanske** [comment]
Seems to be working again, closing the issue unless the error persists, please reopen and specify what's wron with the list then
