### ISSUE TITLE
ListeriaBot returns 502 Bad Gateway error - Requires probably a server restart

### ISSUE THREAD

**Issue by geertivp** [magnusmanske/listeria_rs#97]
Since 2022-12-09 ListeriaBot is returning the following error:

- https://listeria.toolforge.org

```
502 Bad Gateway
nginx/1.14.2
```
It is no longer possible to update tables... do we need a server restart? This type of error frequently occurs... What would be the root cause?

**Comment by geertivp** [comment]
See also https://phabricator.wikimedia.org/T324882

**Comment by eranroz** [comment]
it looks like the web service is down.

**Comment by magnusmanske** [comment]
Seems fixed
