### ISSUE TITLE
Killed by OS for overloading memory

### ISSUE THREAD

**Issue by KajenCAT** [magnusmanske/listeria_rs#99]
In ca.wiki, can't update Listeria list in [Viquiprojecte:Wikidata/Defuncions recents
](https://ca.wikipedia.org/wiki/Viquiprojecte:Wikidata/Defuncions_recents) and it display "Killed by OS for overloading memory" message. Until Dec 17, I could, but the last four days no. How can we solve it?

**Comment by jkjkjkjkjk** [comment]
Try to reduce calling items with lot of labels (countries or towns in your table) from Listeria rather from the query itself  (using rdfs:label). See for example (https://www.wikidata.org/wiki/User:Jklamo/Mesta).

**Comment by sc113** [comment]
In the last month the problem has become more critical. Cutting the labels doesn't help now (I removed countries from the table completely) - now Listeria just always gives this error.

**Comment by magnusmanske** [comment]
Should be fixed now.
